## Find value of killed column only where country == ‘United States’

In [7]:
import csv
import numpy as np

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', 'r', encoding='utf8')
file_data = csv.DictReader(file_obj, skipinitialspace = True)
    
killed=[]
country=[]
for row in file_data:
    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_country = np.array(country)

np_killed[np_killed == ''] = '0.0'

# Convert into float
np_killed = np.array(np_killed, dtype=float)

# convert into int
np_killed = np.array(np_killed, dtype=int)

bool_arr = np_country=='United States'
ans = np_killed[bool_arr]
for i in ans:
    print(i)

2836
2836


## Find total number of people killed from USA

In [9]:
import csv
import numpy as np

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
file_data = csv.DictReader(file_obj, skipinitialspace = True)
    
killed=[]
country=[]
for row in file_data:
    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_country = np.array(country)

# Remove empty spaces
np_killed[np_killed == ''] = '0.0'

# Convert into float bcz we can't directly convert '2.6' in int
np_killed = np.array(np_killed, dtype=float)

# convert into int
np_killed = np.array(np_killed, dtype=int)

bool_arr = np_country=='United States'
ans = np_killed[bool_arr]
print(np.sum(ans))

3771


## Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)

In [11]:
import numpy as np
import csv

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
data = csv.DictReader(file_obj, skipinitialspace=True)

day = []
for row in data:
    day.append(row['Day'])

np_day = np.array(day, dtype=int)

ans = np_day[(np_day>=10) & (np_day<=20)]
print(len(ans))


66330


## Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
## Note Ignore the case where day is 0

In [14]:
import numpy as np
import csv

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
data = csv.DictReader(file_obj, skipinitialspace=True)

day = []
year = []
month = []
for row in data:
    day.append(row['Day'])
    year.append(row['Year'])
    month.append(row['Month'])

np_day = np.array(day, dtype=int)
np_year = np.array(year, dtype=int)
np_month = np.array(month, dtype=int)

ans = np_day[(np_year==2010) & (np_month==1) & (np_day>=1) & (np_day<=31) & (np_day!=0)]
print(len(ans))


271


### As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
### In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
### So find out the attack in this period in which maximum casualties happened.

In [2]:
import numpy as np
import csv

file_obj = open('C:/PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
data = csv.DictReader(file_obj, skipinitialspace=True)

year = []
month = []
killed = []
wounded = []
city = []
group = []

for row in data:
    m, y, s = int(row['Month']), int(row['Year']), row['State']  # Chk filters here otherwise if array becomes Large it cause TLE  
    if (y==1999) and (m>=5) and (m<=7) and (s=='Jammu and Kashmir'):
        killed.append(row['Killed'])
        year.append(y)
        month.append(m)
        wounded.append(row['Wounded'])
        city.append(row['City'])
        group.append(row['Group'])

# Make numpy array
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_city = np.array(city)
np_group = np.array(group)


np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded==''] = '0.0'

# Convert into float
np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

#convert into int
np_killed = np.array(np_killed, dtype = int)
np_wounded = np.array(np_wounded, dtype = int)
np_year = np.array(year, dtype=int)
np_month = np.array(month, dtype=int)

np_casuality = np_killed + np_wounded


ind = np.argmax(np_casuality)
print(np_casuality[ind], np_city[ind], np_group[ind])

22 Kargil District Separatists


## Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
## Note: Casualty=Killed +Wounded

In [54]:
import numpy as np
import csv

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
data = csv.DictReader(file_obj, skipinitialspace=True)

killed = []
wounded = []
state = []
for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    state.append(row['State'])

# Make numpy array
np_killed = np.array(killed)
np_wounded = np.array(wounded)
np_state = np.array(state)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded==''] = '0.0'

# Convert into float
np_killed = np.array(np_killed, dtype = float)
np_wounded = np.array(np_wounded, dtype = float)

#convert into int
np_killed = np.array(np_killed, dtype = int)
np_wounded = np.array(np_wounded, dtype = int)

np_casuality = np_killed + np_wounded

# Find casualty in the Red Corridor States
bool_arr = (np_state == 'Jharkhand') | (np_state == 'Odisha') | (np_state == 'Andhra Pradesh') | (np_state == 'Chhattisgarh')
casuality = np_casuality[bool_arr]
print(np.sum(casuality))

5628


## Find top 5 Indian Cities which has most number of casualties

In [68]:
import numpy as np
import csv

file_obj = open('C:\PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8') # by default is readmode
data = csv.DictReader(file_obj, skipinitialspace=True)

# bcz it is possible that same city is present many times. So to add casulities of all we use dictionary
city_cas = {}

for row in data:
    if row['Country'] == 'India' and row['City'] != 'Unknown': # bcz we have to ignore unknown cities
        killed = row['Killed']
        wounded = row['Wounded']
        city = row['City']
        
        if killed == '':
            killed = 0
        else:
            killed = int(float(killed))
            
        if wounded == '':
            wounded = 0
        else:
            wounded = int(float(wounded))
            
        city_cas[city] = city_cas.get(city, 0) + killed + wounded # Store total casualities of a particular city
    
city = []
casuality = []
for key in city_cas:
    city.append(key)
    casuality.append(city_cas[key])
    
# Make numpy array
np_casuality = np.array(casuality)
np_city = np.array(city)

# Now we have to sort according to casuality
indices = np.argsort(np_casuality) #It gives indices on basis of increasing order of casualities

# Sort acc to decreasing order
cas = np_casuality[indices][::-1] # [::-1] bcz we went to sort in reverse order
cities = np_city[indices][::-1]


# Print top 5 Indian where city!='Unknown'
for i in range(5):
    print(cities[i], cas[i])

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


## Find the most frequent day of attack in a terrorismDataset

In [3]:
import numpy as np
import csv

obj = open('C:/PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/terrorismData.csv', encoding='utf8')
data = csv.DictReader(obj, skipinitialspace=True)

day = []
for row in data:
    day.append(row['Day'])
    
np_day = np.array(day, dtype=int)

unique_days, counts = np.unique(np_day, return_counts=True) #rteurn_counts=True krne se count bhi saath hi mil jjaega for ech distinct element
freq = dict(zip(unique_days, counts))

day_freq = np_day[0] #frequent day
count_freq = freq[np_day[0]] #frequent count

for key in freq:
    if(count_freq < freq[key]):
        count_freq = freq[key]
        day_freq = key
print(day_freq, count_freq)
    

15 6500


### argsort() examples

In [4]:
# sort on basis of 3rd column
a = np.array([[4,1, -2], [2,2,8], [3,2,-7], [1,4,3]])
print(a.shape)
print(a)
b  =np.argsort(a[:,2])
c = a[b]
print(b)
print(c)

(4, 3)
[[ 4  1 -2]
 [ 2  2  8]
 [ 3  2 -7]
 [ 1  4  3]]
[2 0 3 1]
[[ 3  2 -7]
 [ 4  1 -2]
 [ 1  4  3]
 [ 2  2  8]]


In [6]:
#Sort in descending order
a = np.array([23,-6,0,867,87,53])
print(a)
b = np.argsort(a)[::-1]
print(b)
c = a[b]
print(c)

[ 23  -6   0 867  87  53]
[3 4 5 0 2 1]
[867  87  53  23   0  -6]
